apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demo
spec:
  namespaceSelector: {} # discover pods the same namespace as the PodMonitor
  selector:
    matchLabels:
      app.kubernetes.io/instance: demo
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
