apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgbench-init
  namespace: pg-perf
spec:
  suspend: true
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pgbench-init
            image: postgres:17
            command: [ "sh", "-c" ]
            args:
            - |
              echo "Initializing pgbench database..."
              psql -d $PGDATABASE -c '\conninfo'
              pgbench --initialize --scale 10 -h $PGHOST -U $PGUSER $PGDATABASE
              echo "Initialized pgbench database"
            env:
            - name: PGHOST
              value: pg
            - name: PGDATABASE
              value: foo
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: zalando.pg.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: zalando.pg.credentials.postgresql.acid.zalan.do
                  key: password
          restartPolicy: Never
